In [1]:
from scripts.generic_methods import load_dataset
from icecream import ic

DATASET = load_dataset("../data/filtered/analysis.csv", ",")

In [2]:
DATASET.head()

,Unnamed: 0,cardio,is_overweight,bmi_is_valid,is_healthy,ap_lo,years,bmi,height_is_valid,alco,...,ap_hi_status,gluc,is_valid,age_is_valid,weight_is_valid,weight,age_group,ap_hi,gender,cholesterol
0,0,False,False,True,True,80.0,50,21.97,True,False,...,NORMAL,NORMAL,True,True,True,62.0,ADULT,110.0,FEMALE,NORMAL
1,1,True,True,True,False,90.0,55,34.93,True,False,...,HYPERTENSION_STAGE_2,NORMAL,True,True,True,85.0,ADULT,140.0,MALE,WELL_ABOVE_NORMAL
2,2,True,False,True,False,70.0,51,23.51,True,False,...,HYPERTENSION_STAGE_1,NORMAL,True,True,True,64.0,ADULT,130.0,MALE,WELL_ABOVE_NORMAL
3,3,False,False,True,True,60.0,47,23.01,True,False,...,NORMAL,NORMAL,True,True,True,56.0,ADULT,100.0,MALE,NORMAL
4,4,False,True,True,False,80.0,60,29.38,True,False,...,NORMAL,ABOVE_NORMAL,True,True,True,67.0,SENIOR,120.0,MALE,ABOVE_NORMAL

In [5]:
DATASET.columns

Index(['Unnamed: 0', 'cardio', 'is_overweight', 'bmi_is_valid', 'is_healthy',
       'ap_lo', 'years', 'bmi', 'height_is_valid', 'alco', 'active', 'sex',
       'id', 'bmi_status', 'broader_age_group', 'ap_lo_status', 'age', 'smoke',
       'is_underweight', 'height', 'in_hypertension', 'ap_hi_status', 'gluc',
       'is_valid', 'age_is_valid', 'weight_is_valid', 'weight', 'age_group',
       'ap_hi', 'gender', 'cholesterol'],
      dtype='object')

In [4]:
CATEGORICAL = [
    "gluc",
    "age_group",
    "cholesterol",
    "bmi_status",
    "ap_lo_status",
    "ap_hi_status",
]

QUANTITATIVE = [
    "bmi",
    "height",
    "weight",
    "years",
    ""
]